(ghost-parse "concept: ~eat [eat ingest \"binge and purge\"]")
(ghost-parse "concept: ~eat [eat ingest \"binge and purge\"]")
(ghost-parse "concept: ~eat [eat ingest \"binge and purge\"]")
(ghost-parse "concept: ~eat [eat ingest \"binge and purge\"]")
(ghost-parse "u: ( define { \"the word\" (the meaning of) } love ) Sorry. I don’t know it. ^keep")
(ghost-parse "u: ( do you eat _[ ham eggs bacon] ) I eat '_0.")
(ghost-parse "u: ( do you like _* or _* ) I don’t like '_0 so I guess that means I prefer '_1.")
(ghost-parse "u: (you *~2 go *~2 gym) I often go to that gym. ^keep")
(ghost-parse "u: ( do you eat _~meat ) No, I hate _0. ^keep")
(ghost-parse "u: (define {word concept} hate) Sorry. I don't know it. ^keep ")
(ghost-parse "u: (when * you * home) I go home tomorrow ^keep")
(ghost-parse "u: (when *1 you *1 to school) I went to school yesterday ^keep")
(ghost-parse "u: (hello) hello there! ^keep")
(ghost-parse "u: (what be *1) I don't know ^keep")
(ghost-parse "u: ( \" dr. watson \" ) How may I help You?")
(ghost-parse "?: (you [swim ride fish ]) I do ^keep")
(ghost-parse "?: (you [eat ingest \"binge and purge\" (feed my face ) ] meat) I love meat")
(ghost-parse "s: (I ~eat meat) Do you really? I am a vegan.")
